
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  ### The following installs all package files
  packages: !include_dir_named packages
  ### The following installs all customizions 
  customize: !include_dir_merge_named customizations/
# Text to speech
tts:
  - platform: google_translate

lights: !include_dir_list lights
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include_dir_list scenes/
